### ISSUE TITLE
Mask feature / Grant all permissions to mounted folder

### ISSUE THREAD

**Issue by ayalon** [gfi-centre-ouest/vagrant-nfs4j#5]
I have hugh troubles getting the vagrant plugin work.

I would like to achieve the same behaviours as WinNFSd and the same speed. Currently, the daemon is creating this permission.db and maintaining kills the performance. My db is already more than 100MB large.

My need:
I want to mount a folder. All files and folder should be read / write accessible to anyone. The user, the webserver. Basically CHMOD 777 on everything. This is what WinNFSd does.

I tries the mask feature but it did not work:
Mask 0666 results in 1230 while mounting
Mask 0644 results in 1204 while mounting
Mask 777 results in 1411 while mounting
Mask 1000 results in 1750 while mounting.

Is there an easy way to completely skip all the permission handling and grant Read / Write / Execute to everything?

**Comment by Toilal** [comment]
I think i'll change default permission type in next release, but for now you can setup permission type to simple.

in Vagrantfile

`config.nfs4j.shares_config = {:permissions => {:type => 'SIMPLE'}}`

**Comment by ayalon** [comment]
I saw, that you made a new version. Is the permission type now "SIMPLE" per default? Or how can I achieve the same behaviour as WINNFS who does not care about permissions?

**Comment by Toilal** [comment]
Yes, it's now `SIMPLE` per default, and it's been renamed to `DISABLED`. It should now behave like winnfsd when no configuration is defined.

**Comment by devel-pa** [comment]
Hi,

Sorry to post in a closed issue, but is related.
The right number is `0511`

Why?
Somehow the number is taken as decimal and transformed as octal. `511` `=>` `777`

Best,
Paul
